Fix build: switch from `glob.Glob` to `glob.Pattern`
We recently merged https://github.com/numtide/treefmt/pull/726, which
pulled us from glob v0.2.3 → v1.0.0. That includes this big change
<https://github.com/gobwas/glob/commit/c0ec127ffb9903620416663fd8d99f4f834fd492>,
which removed `type Glob` and introduced `type Pattern`. I can't find a
changelog or anything explaining this.

Before:

```
$ go build ./...
format/composite.go:30:24: undefined: glob.Glob
format/formatter.go:48:18: undefined: glob.Glob
format/formatter.go:49:18: undefined: glob.Glob
format/glob.go:10:46: undefined: glob.Glob
format/glob.go:11:23: undefined: glob.Glob
format/glob.go:25:44: undefined: glob.Glob
```

Now things compile =)